### ISSUE TITLE
.eslintrc.json

### ISSUE THREAD

**Issue by CandiceJoy** [origin-1/gulp-eslint-new#1]
Gulp ESLint New doesn't seem to respect .eslintrc.json files...either that or my code is always 100% perfect, even though I have ESLint linting in-IDE throwing warnings :P

**Comment by fasttime** [comment]
Certainly my code is also always 100% perfect 😵 but if you point me to a repo or commit I can have a look.

**Comment by CandiceJoy** [comment]
Whelp, I tried it again and now it works perfectly.  I don't know what I was doing before, my apologies XD

**Comment by fasttime** [comment]
No problem, and happy to hear that you got it working.
