### ISSUE TITLE
Problem with flat config files for eslint 9

### ISSUE THREAD

**Issue by burcadoruciprian** [origin-1/gulp-eslint-new#11]
Hello, 

I have the following task

```
import { src, dest, series, task } from 'gulp';
import eslint from 'gulp-eslint-new';

function lint() {
  return src(['src/**/*.ts']) // Return the stream
    .pipe(eslint({
      overrideConfigFile: 'eslint.config.js', // Point to flat config file
    }))
    .pipe(eslint.format())
    .pipe(eslint.failAfterError());
}

task('lint', lint);
```
When I run it I get the following error: 

```
Error: Cannot read config file: <my_root>/eslint.config.js
```
It eslint 9 currently supported?

Thks

**Comment by fasttime** [comment]
Hi! The latest version of gulp-eslint-new (2.3.0) supports ESLint 9 out of the box. If you have a link to a repo where the error occurs or you can explain how to reproduce the error then I could look into it.

**Comment by burcadoruciprian** [comment]
There was a problem on my end; the config file was actually eslint.config.mjs. It works now. Sorry for wasting you time.
