### ISSUE TITLE
Question: Type Of  gulpESLintNew.result(result)

### ISSUE THREAD

**Issue by Dulux-Oz** [origin-1/gulp-eslint-new#2]
Hi All,

More of a question than an issue (sorry about putting this here but I couldn't think/find a better place/way to ask this):

When running gulp under a TS environment, the line:

```
.pipe(gulpESLintNew.result(result => { some code }
```
gives me the following (truncated) error:
```
error TS7006: Parameter 'result' implicitly has an 'any' type.
```
So my question is: What type should 'result' be for it to not throw up any errors. I've had a look at the `.d.ts` file but I can't work it out (call me stupid, call me ignorant, call me a noob, but I'm (obviously) having trouble getting my head around this).

Thanks in advance
Dulux-Oz

**Comment by fasttime** [comment]
The type should be `GulpESLintResult`, so typing the argument explicitly with `(result: GulpESLintResult) => { some code }` should remove the error.

It's a shame that TypeScript cannot infer the actual type automatically in this case, but this could be fixed by tweaking the type definitions in gulp-eslint-new, so I've marked your issue as an enhancement.

**Comment by Dulux-Oz** [comment]
Thanks for that, I really appreciate it, but now I'm getting other issues:

Here's my (relevant) code:
```
.pipe(gulpESLintNew.result((result:GulpESLintResult) => {
    console.log(`Total Results: ${result.messages.length}`);
    console.log(`Total Warnings: ${result.warningCount} (${result.fixableWarningCount} fixable)`);
    console.log(`Total Errors: ${result.errorCount} (${result.fixableErrorCount} fixable, ${result.fatalErrorCount} fatal)`);
    }))
```
Yeah, its basically a straight copy-&-paste from the documentation.

And here's the error:
```
error TS2304: Cannot find name 'GulpESLintResult'.
    .pipe(gulpESLintNew.result((result:GulpESLintResult) => {
```

**Comment by fasttime** [comment]
`GulpESLintResult` is a type exported by gulp-eslint-new, so you'll have to tell TypeScript to use that type. There are at least four different ways to do so, but what will work for you depends on your TypeScript configuration.

**Comment by fasttime** [comment]
With version 1.4.1 of gulp-eslint-new it is no longer necessary to specify the type of the callback arguments for the functions `result` and `results` to avoid strict TS compiler errors. Thanks for reporting this problem.

**Comment by Dulux-Oz** [comment]
Thanks @fasttime - I really appreciate it.
