### ISSUE TITLE
Error: Cannot find module '#util'

### ISSUE THREAD

**Issue by dclaze** [origin-1/gulp-eslint-new#6]
Getting `MODULE_NOT_FOUND` when requiring `gulp-eslint-new` in my `gulpfile.js`

**package.json**
```
...
"gulp-eslint-new": "^1.6.0",
...
```

**gulpfile.js**
```
const eslint = require('gulp-eslint-new');
```

**Node**
```
% node -v
v12.18.4
% npm -v 
6.14.6
```

**Comment by fasttime** [comment]
Unfortunately, Node.js 12.18 is not supported. The system requirements are defined by ESLint 8 — [see here](https://eslint.org/docs/latest/user-guide/getting-started#prerequisites). You may have success by updating to Node.js 12.22.
